name: SEBAR TV Auto-Updater 🤖

on:
  schedule:
    - cron: '0 */12 * * *' 
  workflow_dispatch: 

jobs:
  update-database:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 هێنانی کۆدەکان
        uses: actions/checkout@v3

      - name: ⚙️ ئامادەکردنی ژینگەی Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📦 داگرتنی ئامرازەکان
        run: npm install

      - name: 🚀 کارپێکردنی مەکینەی ڕاوکردنەکە
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }} # لێرەدا کلیلەکە دەدەین بە بۆتەکە
        run: node bot.js
